[package]
name = "mnema-crypto-sdk-prototype"
version = "0.0.0"
edition = "2024"
rust-version = "1.99"
publish = false

[dependencies]
mnema-private-first-community-bootstrap = { path = "../../checked-storage/bootstrap" }
sframe = { path = "../../../vendor/sframe", default-features = false, features = ["rust-crypto"] }
mnema-crypto-enrollment-prototype = { path = "../../crypto-stack/crypto-enrollment" }
mnema-crypto-trust-candidate = { path = "../../crypto-stack/crypto-trust" }
mnema-crypto-adapter-candidate = { path = "../../crypto-stack/crypto-adapter" }
openmls = { path = "../../../vendor/openmls/openmls" }
openmls_traits = { path = "../../../vendor/openmls/traits" }
openmls_rust_crypto = { path = "../../../vendor/openmls/openmls_rust_crypto" }
openmls_sqlite_storage = { package = "mnema-private-checked-openmls-sqlite-storage", path = "../../checked-storage/checked-sqlite-storage" }
openmls_basic_credential = { path = "../../../vendor/openmls/basic_credential" }
rusqlite = { version = "=0.37.0", features = ["bundled-sqlcipher-vendored-openssl"] }
serde = "=1.0.229"
serde_json = "=1.0.151"
coset = "=0.4.2"
ed25519-dalek = { version = "=2.2.0", default-features = false, features = ["std", "zeroize"] }
zeroize = "=1.9.1"
getrandom = "=0.3.4"
sha2 = "=0.10.9"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "=3.7.0"
security-framework-sys = "=2.17.0"
core-foundation = "=0.10.1"

[dev-dependencies]
tempfile = "=3.23.0"
