// GENERATED by web/scripts/generate-contracts.ts from api/openapi.json.
// Do not edit this file; fix the Go/OpenAPI source and regenerate instead.
import { isRecord, hasOwn, isString, isInteger, isIdentifier, isTimestamp, isArrayOf, decoder } from './validation'

export type AuthAdminUser = {
  avatar_url?: string
  bio: string
  created_at: string
  disabled: boolean
  display_name: string
  id: string
  last_seen_at: string | null
  locale: string
  message_count?: number
  presence?: "online" | "away" | "dnd" | "focus"
  role: "admin" | "user"
  status_text: string
  username: string
  voice_seconds?: number
}

export function isAuthAdminUser(value: unknown): value is AuthAdminUser {
  return isRecord(value)
    && (!hasOwn(value, "avatar_url") || isString(value["avatar_url"]))
    && (hasOwn(value, "bio") && isString(value["bio"], 250))
    && (hasOwn(value, "created_at") && isTimestamp(value["created_at"]))
    && (hasOwn(value, "disabled") && typeof value["disabled"] === 'boolean')
    && (hasOwn(value, "display_name") && isString(value["display_name"], 24))
    && (hasOwn(value, "id") && isIdentifier(value["id"]))
    && (hasOwn(value, "last_seen_at") && (isTimestamp(value["last_seen_at"]) || value["last_seen_at"] === null))
    && (hasOwn(value, "locale") && isString(value["locale"]))
    && (!hasOwn(value, "message_count") || isInteger(value["message_count"]))
    && (!hasOwn(value, "presence") || (value["presence"] === "online" || value["presence"] === "away" || value["presence"] === "dnd" || value["presence"] === "focus"))
    && (hasOwn(value, "role") && (value["role"] === "admin" || value["role"] === "user"))
    && (hasOwn(value, "status_text") && isString(value["status_text"], 32))
    && (hasOwn(value, "username") && isString(value["username"]))
    && (!hasOwn(value, "voice_seconds") || isInteger(value["voice_seconds"]))
}

export const decodeAuthAdminUser = decoder("auth.AdminUser", isAuthAdminUser)

export type AuthChangePasswordRequest = {
  current_password: string
  new_password: string
}

export function isAuthChangePasswordRequest(value: unknown): value is AuthChangePasswordRequest {
  return isRecord(value)
    && (hasOwn(value, "current_password") && isString(value["current_password"]))
    && (hasOwn(value, "new_password") && isString(value["new_password"]))
}

export const decodeAuthChangePasswordRequest = decoder("auth.ChangePasswordRequest", isAuthChangePasswordRequest)

export type AuthCreateInviteRequest = {
  code?: string
  expires_in_hours?: number | null
  max_uses?: number | null
}

export function isAuthCreateInviteRequest(value: unknown): value is AuthCreateInviteRequest {
  return isRecord(value)
    && (!hasOwn(value, "code") || isString(value["code"]))
    && (!hasOwn(value, "expires_in_hours") || (isInteger(value["expires_in_hours"]) || value["expires_in_hours"] === null))
    && (!hasOwn(value, "max_uses") || (isInteger(value["max_uses"]) || value["max_uses"] === null))
}

export const decodeAuthCreateInviteRequest = decoder("auth.CreateInviteRequest", isAuthCreateInviteRequest)

export type AuthInvite = {
  code: string
  created_at: string
  expires_at: string | null
  id: string
  max_uses: number | null
  uses_count: number
}

export function isAuthInvite(value: unknown): value is AuthInvite {
  return isRecord(value)
    && (hasOwn(value, "code") && isString(value["code"]))
    && (hasOwn(value, "created_at") && isTimestamp(value["created_at"]))
    && (hasOwn(value, "expires_at") && (isTimestamp(value["expires_at"]) || value["expires_at"] === null))
    && (hasOwn(value, "id") && isIdentifier(value["id"]))
    && (hasOwn(value, "max_uses") && (isInteger(value["max_uses"]) || value["max_uses"] === null))
    && (hasOwn(value, "uses_count") && isInteger(value["uses_count"]))
}

export const decodeAuthInvite = decoder("auth.Invite", isAuthInvite)

export type AuthLoginRequest = {
  password: string
  username: string
}

export function isAuthLoginRequest(value: unknown): value is AuthLoginRequest {
  return isRecord(value)
    && (hasOwn(value, "password") && isString(value["password"]))
    && (hasOwn(value, "username") && isString(value["username"]))
}

export const decodeAuthLoginRequest = decoder("auth.LoginRequest", isAuthLoginRequest)

export type AuthRegisterRequest = {
  display_name?: string
  invite_code: string
  password: string
  username: string
}

export function isAuthRegisterRequest(value: unknown): value is AuthRegisterRequest {
  return isRecord(value)
    && (!hasOwn(value, "display_name") || isString(value["display_name"], 24))
    && (hasOwn(value, "invite_code") && isString(value["invite_code"], 64))
    && (hasOwn(value, "password") && isString(value["password"]))
    && (hasOwn(value, "username") && isString(value["username"]))
}

export const decodeAuthRegisterRequest = decoder("auth.RegisterRequest", isAuthRegisterRequest)

export type AuthSetLocaleRequest = {
  locale: "de" | "en"
}

export function isAuthSetLocaleRequest(value: unknown): value is AuthSetLocaleRequest {
  return isRecord(value)
    && (hasOwn(value, "locale") && (value["locale"] === "de" || value["locale"] === "en"))
}

export const decodeAuthSetLocaleRequest = decoder("auth.SetLocaleRequest", isAuthSetLocaleRequest)

export type AuthSetPasswordRequest = {
  password: string
}

export function isAuthSetPasswordRequest(value: unknown): value is AuthSetPasswordRequest {
  return isRecord(value)
    && (hasOwn(value, "password") && isString(value["password"]))
}

export const decodeAuthSetPasswordRequest = decoder("auth.SetPasswordRequest", isAuthSetPasswordRequest)

export type AuthSetPresenceRequest = {
  presence: "online" | "away" | "dnd" | "focus"
}

export function isAuthSetPresenceRequest(value: unknown): value is AuthSetPresenceRequest {
  return isRecord(value)
    && (hasOwn(value, "presence") && (value["presence"] === "online" || value["presence"] === "away" || value["presence"] === "dnd" || value["presence"] === "focus"))
}

export const decodeAuthSetPresenceRequest = decoder("auth.SetPresenceRequest", isAuthSetPresenceRequest)

export type AuthSetStatusRequest = {
  status_text: string
}

export function isAuthSetStatusRequest(value: unknown): value is AuthSetStatusRequest {
  return isRecord(value)
    && (hasOwn(value, "status_text") && isString(value["status_text"], 32))
}

export const decodeAuthSetStatusRequest = decoder("auth.SetStatusRequest", isAuthSetStatusRequest)

export type AuthTemporaryPassword = {
  password: string
}

export function isAuthTemporaryPassword(value: unknown): value is AuthTemporaryPassword {
  return isRecord(value)
    && (hasOwn(value, "password") && isString(value["password"]))
}

export const decodeAuthTemporaryPassword = decoder("auth.TemporaryPassword", isAuthTemporaryPassword)

export type AuthUpdateProfileRequest = {
  bio?: string
  display_name?: string
}

export function isAuthUpdateProfileRequest(value: unknown): value is AuthUpdateProfileRequest {
  return isRecord(value)
    && (!hasOwn(value, "bio") || isString(value["bio"], 250))
    && (!hasOwn(value, "display_name") || isString(value["display_name"], 24))
}

export const decodeAuthUpdateProfileRequest = decoder("auth.UpdateProfileRequest", isAuthUpdateProfileRequest)

export type AuthUser = {
  avatar_url?: string
  bio: string
  created_at: string
  display_name: string
  id: string
  locale: string
  message_count?: number
  presence?: "online" | "away" | "dnd" | "focus"
  role: "admin" | "user"
  status_text: string
  username: string
  voice_seconds?: number
}

export function isAuthUser(value: unknown): value is AuthUser {
  return isRecord(value)
    && (!hasOwn(value, "avatar_url") || isString(value["avatar_url"]))
    && (hasOwn(value, "bio") && isString(value["bio"], 250))
    && (hasOwn(value, "created_at") && isTimestamp(value["created_at"]))
    && (hasOwn(value, "display_name") && isString(value["display_name"], 24))
    && (hasOwn(value, "id") && isIdentifier(value["id"]))
    && (hasOwn(value, "locale") && isString(value["locale"]))
    && (!hasOwn(value, "message_count") || isInteger(value["message_count"]))
    && (!hasOwn(value, "presence") || (value["presence"] === "online" || value["presence"] === "away" || value["presence"] === "dnd" || value["presence"] === "focus"))
    && (hasOwn(value, "role") && (value["role"] === "admin" || value["role"] === "user"))
    && (hasOwn(value, "status_text") && isString(value["status_text"], 32))
    && (hasOwn(value, "username") && isString(value["username"]))
    && (!hasOwn(value, "voice_seconds") || isInteger(value["voice_seconds"]))
}

export const decodeAuthUser = decoder("auth.User", isAuthUser)

export type AuthUserEnvelope = {
  user: AuthUser
}

export function isAuthUserEnvelope(value: unknown): value is AuthUserEnvelope {
  return isRecord(value)
    && (hasOwn(value, "user") && isAuthUser(value["user"]))
}

export const decodeAuthUserEnvelope = decoder("auth.UserEnvelope", isAuthUserEnvelope)

export type ChatCategory = {
  channels: Array<ChatChannel>
  created_at: string
  id: string
  name: string
  sort_order: number
}

export function isChatCategory(value: unknown): value is ChatCategory {
  return isRecord(value)
    && (hasOwn(value, "channels") && isArrayOf(value["channels"], item => isChatChannel(item)))
    && (hasOwn(value, "created_at") && isTimestamp(value["created_at"]))
    && (hasOwn(value, "id") && isIdentifier(value["id"]))
    && (hasOwn(value, "name") && isString(value["name"], 64))
    && (hasOwn(value, "sort_order") && isInteger(value["sort_order"]))
}

export const decodeChatCategory = decoder("chat.Category", isChatCategory)

export type ChatCategoryOrder = {
  id: string
  sort_order: number
}

export function isChatCategoryOrder(value: unknown): value is ChatCategoryOrder {
  return isRecord(value)
    && (hasOwn(value, "id") && isIdentifier(value["id"]))
    && (hasOwn(value, "sort_order") && isInteger(value["sort_order"]))
}

export const decodeChatCategoryOrder = decoder("chat.CategoryOrder", isChatCategoryOrder)

export type ChatChannel = {
  category_id: string | null
  created_at: string
  id: string
  name: string
  sort_order: number
  topic: string
  type: ChatChannelType
}

export function isChatChannel(value: unknown): value is ChatChannel {
  return isRecord(value)
    && (hasOwn(value, "category_id") && (isIdentifier(value["category_id"]) || value["category_id"] === null))
    && (hasOwn(value, "created_at") && isTimestamp(value["created_at"]))
    && (hasOwn(value, "id") && isIdentifier(value["id"]))
    && (hasOwn(value, "name") && isString(value["name"], 64))
    && (hasOwn(value, "sort_order") && isInteger(value["sort_order"]))
    && (hasOwn(value, "topic") && isString(value["topic"], 255))
    && (hasOwn(value, "type") && isChatChannelType(value["type"]))
}

export const decodeChatChannel = decoder("chat.Channel", isChatChannel)

export type ChatChannelHierarchy = {
  categories: Array<ChatCategory>
  uncategorized: Array<ChatChannel>
}

export function isChatChannelHierarchy(value: unknown): value is ChatChannelHierarchy {
  return isRecord(value)
    && (hasOwn(value, "categories") && isArrayOf(value["categories"], item => isChatCategory(item)))
    && (hasOwn(value, "uncategorized") && isArrayOf(value["uncategorized"], item => isChatChannel(item)))
}

export const decodeChatChannelHierarchy = decoder("chat.ChannelHierarchy", isChatChannelHierarchy)

export type ChatChannelPlacement = {
  category_id: string | null
  id: string
  sort_order: number
}

export function isChatChannelPlacement(value: unknown): value is ChatChannelPlacement {
  return isRecord(value)
    && (hasOwn(value, "category_id") && (isIdentifier(value["category_id"]) || value["category_id"] === null))
    && (hasOwn(value, "id") && isIdentifier(value["id"]))
    && (hasOwn(value, "sort_order") && isInteger(value["sort_order"]))
}

export const decodeChatChannelPlacement = decoder("chat.ChannelPlacement", isChatChannelPlacement)

export type ChatChannelType = "text" | "voice"

export function isChatChannelType(value: unknown): value is ChatChannelType {
  return (value === "text" || value === "voice")
}

export const decodeChatChannelType = decoder("chat.ChannelType", isChatChannelType)

export type ChatCreateCategoryRequest = {
  name: string
  sort_order?: number
}

export function isChatCreateCategoryRequest(value: unknown): value is ChatCreateCategoryRequest {
  return isRecord(value)
    && (hasOwn(value, "name") && isString(value["name"], 64))
    && (!hasOwn(value, "sort_order") || isInteger(value["sort_order"]))
}

export const decodeChatCreateCategoryRequest = decoder("chat.CreateCategoryRequest", isChatCreateCategoryRequest)

export type ChatCreateChannelRequest = {
  category_id?: string | null
  name: string
  sort_order?: number
  topic?: string
  type?: ChatChannelType
}

export function isChatCreateChannelRequest(value: unknown): value is ChatCreateChannelRequest {
  return isRecord(value)
    && (!hasOwn(value, "category_id") || (isIdentifier(value["category_id"]) || value["category_id"] === null))
    && (hasOwn(value, "name") && isString(value["name"], 64))
    && (!hasOwn(value, "sort_order") || isInteger(value["sort_order"]))
    && (!hasOwn(value, "topic") || isString(value["topic"], 255))
    && (!hasOwn(value, "type") || isChatChannelType(value["type"]))
}

export const decodeChatCreateChannelRequest = decoder("chat.CreateChannelRequest", isChatCreateChannelRequest)

export type ChatCreateMessageRequest = {
  content: string
  parent_id?: string | null
  reply_to_id?: string | null
}

export function isChatCreateMessageRequest(value: unknown): value is ChatCreateMessageRequest {
  return isRecord(value)
    && (hasOwn(value, "content") && isString(value["content"], 4000))
    && (!hasOwn(value, "parent_id") || (isIdentifier(value["parent_id"]) || value["parent_id"] === null))
    && (!hasOwn(value, "reply_to_id") || (isIdentifier(value["reply_to_id"]) || value["reply_to_id"] === null))
}

export const decodeChatCreateMessageRequest = decoder("chat.CreateMessageRequest", isChatCreateMessageRequest)

export type ChatEditMessageRequest = {
  content: string
}

export function isChatEditMessageRequest(value: unknown): value is ChatEditMessageRequest {
  return isRecord(value)
    && (hasOwn(value, "content") && isString(value["content"], 4000))
}

export const decodeChatEditMessageRequest = decoder("chat.EditMessageRequest", isChatEditMessageRequest)

export type ChatLayoutRequest = {
  categories?: Array<ChatCategoryOrder>
  channels?: Array<ChatChannelPlacement>
}

export function isChatLayoutRequest(value: unknown): value is ChatLayoutRequest {
  return isRecord(value)
    && (!hasOwn(value, "categories") || isArrayOf(value["categories"], item => isChatCategoryOrder(item)))
    && (!hasOwn(value, "channels") || isArrayOf(value["channels"], item => isChatChannelPlacement(item)))
}

export const decodeChatLayoutRequest = decoder("chat.LayoutRequest", isChatLayoutRequest)

export type ChatMarkReadRequest = {
  message_id?: string | null
}

export function isChatMarkReadRequest(value: unknown): value is ChatMarkReadRequest {
  return isRecord(value)
    && (!hasOwn(value, "message_id") || (isIdentifier(value["message_id"]) || value["message_id"] === null))
}

export const decodeChatMarkReadRequest = decoder("chat.MarkReadRequest", isChatMarkReadRequest)

export type ChatMarkUnreadRequest = {
  message_id: string
}

export function isChatMarkUnreadRequest(value: unknown): value is ChatMarkUnreadRequest {
  return isRecord(value)
    && (hasOwn(value, "message_id") && isIdentifier(value["message_id"]))
}

export const decodeChatMarkUnreadRequest = decoder("chat.MarkUnreadRequest", isChatMarkUnreadRequest)

export type ChatMediaAttachment = {
  id: string
  is_deleted: boolean
  mime_type: string
  original_filename: string
  size_bytes: number
  url: string
}

export function isChatMediaAttachment(value: unknown): value is ChatMediaAttachment {
  return isRecord(value)
    && (hasOwn(value, "id") && isIdentifier(value["id"]))
    && (hasOwn(value, "is_deleted") && typeof value["is_deleted"] === 'boolean')
    && (hasOwn(value, "mime_type") && isString(value["mime_type"]))
    && (hasOwn(value, "original_filename") && isString(value["original_filename"]))
    && (hasOwn(value, "size_bytes") && isInteger(value["size_bytes"]))
    && (hasOwn(value, "url") && isString(value["url"]))
}

export const decodeChatMediaAttachment = decoder("chat.MediaAttachment", isChatMediaAttachment)

export type ChatMessage = {
  attachments: Array<ChatMediaAttachment>
  avatar_url?: string
  channel_id: string
  content: string
  created_at: string
  display_name: string
  id: string
  is_edited: boolean
  is_pinned: boolean
  mentions: Array<string>
  parent_id?: string
  reactions: Array<ChatReactionSummary>
  reply_count: number
  reply_to?: ChatReplyPreview
  reply_to_id?: string
  updated_at: string
  user_id: string
  username: string
}

export function isChatMessage(value: unknown): value is ChatMessage {
  return isRecord(value)
    && (hasOwn(value, "attachments") && isArrayOf(value["attachments"], item => isChatMediaAttachment(item)))
    && (!hasOwn(value, "avatar_url") || isString(value["avatar_url"]))
    && (hasOwn(value, "channel_id") && isIdentifier(value["channel_id"]))
    && (hasOwn(value, "content") && isString(value["content"], 4000))
    && (hasOwn(value, "created_at") && isTimestamp(value["created_at"]))
    && (hasOwn(value, "display_name") && isString(value["display_name"]))
    && (hasOwn(value, "id") && isIdentifier(value["id"]))
    && (hasOwn(value, "is_edited") && typeof value["is_edited"] === 'boolean')
    && (hasOwn(value, "is_pinned") && typeof value["is_pinned"] === 'boolean')
    && (hasOwn(value, "mentions") && isArrayOf(value["mentions"], item => isIdentifier(item)))
    && (!hasOwn(value, "parent_id") || isIdentifier(value["parent_id"]))
    && (hasOwn(value, "reactions") && isArrayOf(value["reactions"], item => isChatReactionSummary(item)))
    && (hasOwn(value, "reply_count") && isInteger(value["reply_count"]))
    && (!hasOwn(value, "reply_to") || isChatReplyPreview(value["reply_to"]))
    && (!hasOwn(value, "reply_to_id") || isIdentifier(value["reply_to_id"]))
    && (hasOwn(value, "updated_at") && isTimestamp(value["updated_at"]))
    && (hasOwn(value, "user_id") && isIdentifier(value["user_id"]))
    && (hasOwn(value, "username") && isString(value["username"]))
}

export const decodeChatMessage = decoder("chat.Message", isChatMessage)

export type ChatNotifyLevel = "all" | "mentions" | "mute"

export function isChatNotifyLevel(value: unknown): value is ChatNotifyLevel {
  return (value === "all" || value === "mentions" || value === "mute")
}

export const decodeChatNotifyLevel = decoder("chat.NotifyLevel", isChatNotifyLevel)

export type ChatReactionRequest = {
  emoji: string
}

export function isChatReactionRequest(value: unknown): value is ChatReactionRequest {
  return isRecord(value)
    && (hasOwn(value, "emoji") && isString(value["emoji"], 32))
}

export const decodeChatReactionRequest = decoder("chat.ReactionRequest", isChatReactionRequest)

export type ChatReactionResult = {
  message_id: string
  reactions: Array<ChatReactionSummary>
}

export function isChatReactionResult(value: unknown): value is ChatReactionResult {
  return isRecord(value)
    && (hasOwn(value, "message_id") && isIdentifier(value["message_id"]))
    && (hasOwn(value, "reactions") && isArrayOf(value["reactions"], item => isChatReactionSummary(item)))
}

export const decodeChatReactionResult = decoder("chat.ReactionResult", isChatReactionResult)

export type ChatReactionSummary = {
  count: number
  emoji: string
  users: Array<string>
}

export function isChatReactionSummary(value: unknown): value is ChatReactionSummary {
  return isRecord(value)
    && (hasOwn(value, "count") && isInteger(value["count"]))
    && (hasOwn(value, "emoji") && isString(value["emoji"]))
    && (hasOwn(value, "users") && isArrayOf(value["users"], item => isIdentifier(item)))
}

export const decodeChatReactionSummary = decoder("chat.ReactionSummary", isChatReactionSummary)

export type ChatReadState = {
  channel_id: string
  last_read_at: string | null
  mention_count: number
  notify_level: ChatNotifyLevel
  unread_count: number
}

export function isChatReadState(value: unknown): value is ChatReadState {
  return isRecord(value)
    && (hasOwn(value, "channel_id") && isIdentifier(value["channel_id"]))
    && (hasOwn(value, "last_read_at") && (isTimestamp(value["last_read_at"]) || value["last_read_at"] === null))
    && (hasOwn(value, "mention_count") && isInteger(value["mention_count"]))
    && (hasOwn(value, "notify_level") && isChatNotifyLevel(value["notify_level"]))
    && (hasOwn(value, "unread_count") && isInteger(value["unread_count"]))
}

export const decodeChatReadState = decoder("chat.ReadState", isChatReadState)

export type ChatRenameCategoryRequest = {
  name: string
}

export function isChatRenameCategoryRequest(value: unknown): value is ChatRenameCategoryRequest {
  return isRecord(value)
    && (hasOwn(value, "name") && isString(value["name"], 64))
}

export const decodeChatRenameCategoryRequest = decoder("chat.RenameCategoryRequest", isChatRenameCategoryRequest)

export type ChatRenamedCategory = {
  id: string
  name: string
}

export function isChatRenamedCategory(value: unknown): value is ChatRenamedCategory {
  return isRecord(value)
    && (hasOwn(value, "id") && isIdentifier(value["id"]))
    && (hasOwn(value, "name") && isString(value["name"]))
}

export const decodeChatRenamedCategory = decoder("chat.RenamedCategory", isChatRenamedCategory)

export type ChatReplyPreview = {
  avatar_url?: string
  content?: string
  deleted: boolean
  display_name?: string
  has_attachments?: boolean
  id: string
  user_id?: string
  username?: string
}

export function isChatReplyPreview(value: unknown): value is ChatReplyPreview {
  return isRecord(value)
    && (!hasOwn(value, "avatar_url") || isString(value["avatar_url"]))
    && (!hasOwn(value, "content") || isString(value["content"]))
    && (hasOwn(value, "deleted") && typeof value["deleted"] === 'boolean')
    && (!hasOwn(value, "display_name") || isString(value["display_name"]))
    && (!hasOwn(value, "has_attachments") || typeof value["has_attachments"] === 'boolean')
    && (hasOwn(value, "id") && isIdentifier(value["id"]))
    && (!hasOwn(value, "user_id") || isIdentifier(value["user_id"]))
    && (!hasOwn(value, "username") || isString(value["username"]))
}

export const decodeChatReplyPreview = decoder("chat.ReplyPreview", isChatReplyPreview)

export type ChatSearchResult = {
  has_more: boolean
  messages: Array<ChatMessage>
}

export function isChatSearchResult(value: unknown): value is ChatSearchResult {
  return isRecord(value)
    && (hasOwn(value, "has_more") && typeof value["has_more"] === 'boolean')
    && (hasOwn(value, "messages") && isArrayOf(value["messages"], item => isChatMessage(item)))
}

export const decodeChatSearchResult = decoder("chat.SearchResult", isChatSearchResult)

export type ChatSetNotifyLevelRequest = {
  level: ChatNotifyLevel
}

export function isChatSetNotifyLevelRequest(value: unknown): value is ChatSetNotifyLevelRequest {
  return isRecord(value)
    && (hasOwn(value, "level") && isChatNotifyLevel(value["level"]))
}

export const decodeChatSetNotifyLevelRequest = decoder("chat.SetNotifyLevelRequest", isChatSetNotifyLevelRequest)

export type ChatThread = {
  replies: Array<ChatMessage>
  root: ChatMessage
}

export function isChatThread(value: unknown): value is ChatThread {
  return isRecord(value)
    && (hasOwn(value, "replies") && isArrayOf(value["replies"], item => isChatMessage(item)))
    && (hasOwn(value, "root") && isChatMessage(value["root"]))
}

export const decodeChatThread = decoder("chat.Thread", isChatThread)

export type ChatUpdateChannelRequest = {
  name?: string
  topic?: string
}

export function isChatUpdateChannelRequest(value: unknown): value is ChatUpdateChannelRequest {
  return isRecord(value)
    && (!hasOwn(value, "name") || isString(value["name"], 64))
    && (!hasOwn(value, "topic") || isString(value["topic"], 255))
}

export const decodeChatUpdateChannelRequest = decoder("chat.UpdateChannelRequest", isChatUpdateChannelRequest)

export type HttpxAPIError = {
  code: "INVALID_INPUT" | "UNAUTHORIZED" | "INVALID_CREDENTIALS" | "FORBIDDEN" | "ACCOUNT_DISABLED" | "NOT_FOUND" | "CONFLICT" | "PAYLOAD_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE" | "RATE_LIMITED" | "UNAVAILABLE" | "INTERNAL_ERROR"
  message: string
}

export function isHttpxAPIError(value: unknown): value is HttpxAPIError {
  return isRecord(value)
    && (hasOwn(value, "code") && (value["code"] === "INVALID_INPUT" || value["code"] === "UNAUTHORIZED" || value["code"] === "INVALID_CREDENTIALS" || value["code"] === "FORBIDDEN" || value["code"] === "ACCOUNT_DISABLED" || value["code"] === "NOT_FOUND" || value["code"] === "CONFLICT" || value["code"] === "PAYLOAD_TOO_LARGE" || value["code"] === "UNSUPPORTED_MEDIA_TYPE" || value["code"] === "RATE_LIMITED" || value["code"] === "UNAVAILABLE" || value["code"] === "INTERNAL_ERROR"))
    && (hasOwn(value, "message") && isString(value["message"]))
}

export const decodeHttpxAPIError = decoder("httpx.APIError", isHttpxAPIError)

export type HttpxErrorResponse = {
  error: HttpxAPIError
}

export function isHttpxErrorResponse(value: unknown): value is HttpxErrorResponse {
  return isRecord(value)
    && (hasOwn(value, "error") && isHttpxAPIError(value["error"]))
}

export const decodeHttpxErrorResponse = decoder("httpx.ErrorResponse", isHttpxErrorResponse)

export type LinkpreviewPreview = {
  description?: string
  image?: string
  site_name?: string
  title: string
  url: string
}

export function isLinkpreviewPreview(value: unknown): value is LinkpreviewPreview {
  return isRecord(value)
    && (!hasOwn(value, "description") || isString(value["description"]))
    && (!hasOwn(value, "image") || isString(value["image"]))
    && (!hasOwn(value, "site_name") || isString(value["site_name"]))
    && (hasOwn(value, "title") && isString(value["title"]))
    && (hasOwn(value, "url") && isString(value["url"]))
}

export const decodeLinkpreviewPreview = decoder("linkpreview.Preview", isLinkpreviewPreview)

export type MediaDashboardItem = {
  channel_id: string | null
  channel_name?: string
  created_at: string
  id: string
  is_deleted: boolean
  mime_type: string
  original_filename: string
  size_bytes: number
  uploader_id: string
  uploader_name: string
  url: string
}

export function isMediaDashboardItem(value: unknown): value is MediaDashboardItem {
  return isRecord(value)
    && (hasOwn(value, "channel_id") && (isIdentifier(value["channel_id"]) || value["channel_id"] === null))
    && (!hasOwn(value, "channel_name") || isString(value["channel_name"]))
    && (hasOwn(value, "created_at") && isTimestamp(value["created_at"]))
    && (hasOwn(value, "id") && isIdentifier(value["id"]))
    && (hasOwn(value, "is_deleted") && typeof value["is_deleted"] === 'boolean')
    && (hasOwn(value, "mime_type") && isString(value["mime_type"]))
    && (hasOwn(value, "original_filename") && isString(value["original_filename"]))
    && (hasOwn(value, "size_bytes") && isInteger(value["size_bytes"]))
    && (hasOwn(value, "uploader_id") && isIdentifier(value["uploader_id"]))
    && (hasOwn(value, "uploader_name") && isString(value["uploader_name"]))
    && (hasOwn(value, "url") && isString(value["url"]))
}

export const decodeMediaDashboardItem = decoder("media.DashboardItem", isMediaDashboardItem)

export type MediaPruneResult = {
  cutoff_days: number
  pruned_count: number
}

export function isMediaPruneResult(value: unknown): value is MediaPruneResult {
  return isRecord(value)
    && (hasOwn(value, "cutoff_days") && isInteger(value["cutoff_days"]))
    && (hasOwn(value, "pruned_count") && isInteger(value["pruned_count"]))
}

export const decodeMediaPruneResult = decoder("media.PruneResult", isMediaPruneResult)

export type MediaStats = {
  deleted_files: number
  total_files: number
  total_size_bytes: number
}

export function isMediaStats(value: unknown): value is MediaStats {
  return isRecord(value)
    && (hasOwn(value, "deleted_files") && isInteger(value["deleted_files"]))
    && (hasOwn(value, "total_files") && isInteger(value["total_files"]))
    && (hasOwn(value, "total_size_bytes") && isInteger(value["total_size_bytes"]))
}

export const decodeMediaStats = decoder("media.Stats", isMediaStats)

export type ServerDatabaseHealth = {
  applied_migrations: number
  latest_migration: string
  pending_migrations: number
  reachable: boolean
}

export function isServerDatabaseHealth(value: unknown): value is ServerDatabaseHealth {
  return isRecord(value)
    && (hasOwn(value, "applied_migrations") && isInteger(value["applied_migrations"]))
    && (hasOwn(value, "latest_migration") && isString(value["latest_migration"]))
    && (hasOwn(value, "pending_migrations") && isInteger(value["pending_migrations"]))
    && (hasOwn(value, "reachable") && typeof value["reachable"] === 'boolean')
}

export const decodeServerDatabaseHealth = decoder("server.DatabaseHealth", isServerDatabaseHealth)

export type ServerHealth = {
  status: "ok"
  version: string
}

export function isServerHealth(value: unknown): value is ServerHealth {
  return isRecord(value)
    && (hasOwn(value, "status") && (value["status"] === "ok"))
    && (hasOwn(value, "version") && isString(value["version"]))
}

export const decodeServerHealth = decoder("server.Health", isServerHealth)

export type ServerICEConfig = {
  ice_servers: Array<ServerIceServer>
}

export function isServerICEConfig(value: unknown): value is ServerICEConfig {
  return isRecord(value)
    && (hasOwn(value, "ice_servers") && isArrayOf(value["ice_servers"], item => isServerIceServer(item)))
}

export const decodeServerICEConfig = decoder("server.ICEConfig", isServerICEConfig)

export type ServerIceServer = {
  credential?: string
  urls: Array<string>
  username?: string
}

export function isServerIceServer(value: unknown): value is ServerIceServer {
  return isRecord(value)
    && (!hasOwn(value, "credential") || isString(value["credential"]))
    && (hasOwn(value, "urls") && isArrayOf(value["urls"], item => isString(item)))
    && (!hasOwn(value, "username") || isString(value["username"]))
}

export const decodeServerIceServer = decoder("server.IceServer", isServerIceServer)

export type ServerLegal = {
  legal_version: string
  media_retention_days: number
  operator_country: string
  operator_email: string
  operator_name: string
  project_notice: string
  session_expiry_days: number
  stun_servers: Array<string>
  turn_servers: Array<string>
  update_check: boolean
}

export function isServerLegal(value: unknown): value is ServerLegal {
  return isRecord(value)
    && (hasOwn(value, "legal_version") && isString(value["legal_version"]))
    && (hasOwn(value, "media_retention_days") && isInteger(value["media_retention_days"]))
    && (hasOwn(value, "operator_country") && isString(value["operator_country"]))
    && (hasOwn(value, "operator_email") && isString(value["operator_email"]))
    && (hasOwn(value, "operator_name") && isString(value["operator_name"]))
    && (hasOwn(value, "project_notice") && isString(value["project_notice"]))
    && (hasOwn(value, "session_expiry_days") && isInteger(value["session_expiry_days"]))
    && (hasOwn(value, "stun_servers") && isArrayOf(value["stun_servers"], item => isString(item)))
    && (hasOwn(value, "turn_servers") && isArrayOf(value["turn_servers"], item => isString(item)))
    && (hasOwn(value, "update_check") && typeof value["update_check"] === 'boolean')
}

export const decodeServerLegal = decoder("server.Legal", isServerLegal)

export type ServerRuntimeHealth = {
  go_version: string
  goroutines: number
  mem_alloc_bytes: number
  mem_sys_bytes: number
  started_at: string
  uptime_seconds: number
}

export function isServerRuntimeHealth(value: unknown): value is ServerRuntimeHealth {
  return isRecord(value)
    && (hasOwn(value, "go_version") && isString(value["go_version"]))
    && (hasOwn(value, "goroutines") && isInteger(value["goroutines"]))
    && (hasOwn(value, "mem_alloc_bytes") && isInteger(value["mem_alloc_bytes"]))
    && (hasOwn(value, "mem_sys_bytes") && isInteger(value["mem_sys_bytes"]))
    && (hasOwn(value, "started_at") && isTimestamp(value["started_at"]))
    && (hasOwn(value, "uptime_seconds") && isInteger(value["uptime_seconds"]))
}

export const decodeServerRuntimeHealth = decoder("server.RuntimeHealth", isServerRuntimeHealth)

export type ServerSelfUpdateRequest = {
  password: string
  target_version: string
}

export function isServerSelfUpdateRequest(value: unknown): value is ServerSelfUpdateRequest {
  return isRecord(value)
    && (hasOwn(value, "password") && isString(value["password"]))
    && (hasOwn(value, "target_version") && isString(value["target_version"]))
}

export const decodeServerSelfUpdateRequest = decoder("server.SelfUpdateRequest", isServerSelfUpdateRequest)

export type ServerSelfUpdateStarted = {
  from_version: string
  status: "started"
  target_version: string
}

export function isServerSelfUpdateStarted(value: unknown): value is ServerSelfUpdateStarted {
  return isRecord(value)
    && (hasOwn(value, "from_version") && isString(value["from_version"]))
    && (hasOwn(value, "status") && (value["status"] === "started"))
    && (hasOwn(value, "target_version") && isString(value["target_version"]))
}

export const decodeServerSelfUpdateStarted = decoder("server.SelfUpdateStarted", isServerSelfUpdateStarted)

export type ServerSelfUpdateStatus = {
  available: boolean
  configured: boolean
  image: string
  next_allowed_at: string | null
  reach: "yes" | "no" | "unknown"
  reach_reason: "follows" | "unset" | "local_build" | "digest_pinned" | "version_pinned" | "track_mismatch" | "custom_tag"
}

export function isServerSelfUpdateStatus(value: unknown): value is ServerSelfUpdateStatus {
  return isRecord(value)
    && (hasOwn(value, "available") && typeof value["available"] === 'boolean')
    && (hasOwn(value, "configured") && typeof value["configured"] === 'boolean')
    && (hasOwn(value, "image") && isString(value["image"]))
    && (hasOwn(value, "next_allowed_at") && (isTimestamp(value["next_allowed_at"]) || value["next_allowed_at"] === null))
    && (hasOwn(value, "reach") && (value["reach"] === "yes" || value["reach"] === "no" || value["reach"] === "unknown"))
    && (hasOwn(value, "reach_reason") && (value["reach_reason"] === "follows" || value["reach_reason"] === "unset" || value["reach_reason"] === "local_build" || value["reach_reason"] === "digest_pinned" || value["reach_reason"] === "version_pinned" || value["reach_reason"] === "track_mismatch" || value["reach_reason"] === "custom_tag"))
}

export const decodeServerSelfUpdateStatus = decoder("server.SelfUpdateStatus", isServerSelfUpdateStatus)

export type ServerStorageHealth = {
  attachment_bytes: number
  avatar_bytes: number
  configured: boolean
  files: number
  reachable: boolean
  total_bytes: number
}

export function isServerStorageHealth(value: unknown): value is ServerStorageHealth {
  return isRecord(value)
    && (hasOwn(value, "attachment_bytes") && isInteger(value["attachment_bytes"]))
    && (hasOwn(value, "avatar_bytes") && isInteger(value["avatar_bytes"]))
    && (hasOwn(value, "configured") && typeof value["configured"] === 'boolean')
    && (hasOwn(value, "files") && isInteger(value["files"]))
    && (hasOwn(value, "reachable") && typeof value["reachable"] === 'boolean')
    && (hasOwn(value, "total_bytes") && isInteger(value["total_bytes"]))
}

export const decodeServerStorageHealth = decoder("server.StorageHealth", isServerStorageHealth)

export type ServerSystemHealth = {
  database: ServerDatabaseHealth
  runtime: ServerRuntimeHealth
  storage: ServerStorageHealth
  voice: ServerVoiceHealth
}

export function isServerSystemHealth(value: unknown): value is ServerSystemHealth {
  return isRecord(value)
    && (hasOwn(value, "database") && isServerDatabaseHealth(value["database"]))
    && (hasOwn(value, "runtime") && isServerRuntimeHealth(value["runtime"]))
    && (hasOwn(value, "storage") && isServerStorageHealth(value["storage"]))
    && (hasOwn(value, "voice") && isServerVoiceHealth(value["voice"]))
}

export const decodeServerSystemHealth = decoder("server.SystemHealth", isServerSystemHealth)

export type ServerSystemStatus = {
  health: ServerSystemHealth
  self_update: ServerSelfUpdateStatus
  update: ServerUpdateStatus
  version: ServerSystemVersion
}

export function isServerSystemStatus(value: unknown): value is ServerSystemStatus {
  return isRecord(value)
    && (hasOwn(value, "health") && isServerSystemHealth(value["health"]))
    && (hasOwn(value, "self_update") && isServerSelfUpdateStatus(value["self_update"]))
    && (hasOwn(value, "update") && isServerUpdateStatus(value["update"]))
    && (hasOwn(value, "version") && isServerSystemVersion(value["version"]))
}

export const decodeServerSystemStatus = decoder("server.SystemStatus", isServerSystemStatus)

export type ServerSystemVersion = {
  current: string
  go_version: string
  revision: string
}

export function isServerSystemVersion(value: unknown): value is ServerSystemVersion {
  return isRecord(value)
    && (hasOwn(value, "current") && isString(value["current"]))
    && (hasOwn(value, "go_version") && isString(value["go_version"]))
    && (hasOwn(value, "revision") && isString(value["revision"]))
}

export const decodeServerSystemVersion = decoder("server.SystemVersion", isServerSystemVersion)

export type ServerUpdateStatus = {
  check_enabled: boolean
  check_error: string
  checked_at: string | null
  current_version: string
  latest_version: string
  published_at: string | null
  release_notes: string
  release_url: string
  retry_at: string | null
  update_available: boolean
}

export function isServerUpdateStatus(value: unknown): value is ServerUpdateStatus {
  return isRecord(value)
    && (hasOwn(value, "check_enabled") && typeof value["check_enabled"] === 'boolean')
    && (hasOwn(value, "check_error") && isString(value["check_error"]))
    && (hasOwn(value, "checked_at") && (isTimestamp(value["checked_at"]) || value["checked_at"] === null))
    && (hasOwn(value, "current_version") && isString(value["current_version"]))
    && (hasOwn(value, "latest_version") && isString(value["latest_version"]))
    && (hasOwn(value, "published_at") && (isTimestamp(value["published_at"]) || value["published_at"] === null))
    && (hasOwn(value, "release_notes") && isString(value["release_notes"]))
    && (hasOwn(value, "release_url") && isString(value["release_url"]))
    && (hasOwn(value, "retry_at") && (isTimestamp(value["retry_at"]) || value["retry_at"] === null))
    && (hasOwn(value, "update_available") && typeof value["update_available"] === 'boolean')
}

export const decodeServerUpdateStatus = decoder("server.UpdateStatus", isServerUpdateStatus)

export type ServerVoiceHealth = {
  cameras: number
  enabled: boolean
  media_connections: number
  online_users: number
  participants: number
  rooms: number
  screen_shares: number
  stun_configured: boolean
  turn_configured: boolean
  websocket_connections: number
}

export function isServerVoiceHealth(value: unknown): value is ServerVoiceHealth {
  return isRecord(value)
    && (hasOwn(value, "cameras") && isInteger(value["cameras"]))
    && (hasOwn(value, "enabled") && typeof value["enabled"] === 'boolean')
    && (hasOwn(value, "media_connections") && isInteger(value["media_connections"]))
    && (hasOwn(value, "online_users") && isInteger(value["online_users"]))
    && (hasOwn(value, "participants") && isInteger(value["participants"]))
    && (hasOwn(value, "rooms") && isInteger(value["rooms"]))
    && (hasOwn(value, "screen_shares") && isInteger(value["screen_shares"]))
    && (hasOwn(value, "stun_configured") && typeof value["stun_configured"] === 'boolean')
    && (hasOwn(value, "turn_configured") && typeof value["turn_configured"] === 'boolean')
    && (hasOwn(value, "websocket_connections") && isInteger(value["websocket_connections"]))
}

export const decodeServerVoiceHealth = decoder("server.VoiceHealth", isServerVoiceHealth)
